/** Public component families, kept independent of the live preview implementation. */
export interface CatalogueVariant {
  name: string;
  values: string[];
  default?: string;
}
export interface ComponentCatalogueEntry {
  id: string;
  name: string;
  category: string;
  description: string;
  purpose: string;
  usage: string;
  importPath: string;
  code: string;
  anatomy: string[];
  variants: CatalogueVariant[];
  docsUrl: string;
  keywords: string[];
}
export const catalogueCategories = [
  'Actions',
  'Forms',
  'Navigation',
  'Data display',
  'Data grid',
  'Charts',
  'Code',
  'Overlays',
  'Feedback',
  'Layout',
  'AI',
  'Brand & icons',
];
export const catalogueCategoryIds: Record<string, string> = {
  Actions: 'actions',
  Forms: 'forms',
  Navigation: 'navigation',
  'Data display': 'data-display',
  'Data grid': 'data-grid',
  Charts: 'charts',
  Code: 'code',
  Overlays: 'overlays',
  Feedback: 'feedback',
  Layout: 'layout',
  AI: 'ai',
  'Brand & icons': 'brand-icons',
};
const packageName = '@dimitriszoitas/aegis-ui';
const docsBase = 'https://dimitriszoitas.github.io/aegis-ui/?path=/docs/';
const v = (name: string, values: string[], defaultValue?: string): CatalogueVariant => ({
  name,
  values,
  ...(defaultValue === undefined ? {} : { default: defaultValue }),
});
interface Example {
  exports: string;
  jsx: string;
  setup?: string;
  imports?: string[];
  subpath?: string;
}
function entry(
  id: string,
  name: string,
  category: string,
  description: string,
  usage: string,
  anatomy: string[],
  example: Example,
  story: string,
  variants: CatalogueVariant[] = [],
  keywords: string[] = [],
): ComponentCatalogueEntry {
  const importPath = `${packageName}/${example.subpath ?? id}`;
  const code = [
    ...(example.setup?.includes('useState') ? ["import { useState } from 'react';"] : []),
    `import { ${example.exports} } from '${importPath}';`,
    ...(example.imports ?? []),
    `import '${packageName}/styles.css';`,
    '',
    'export default function Example() {',
    ...(example.setup ? example.setup.split('\n').map((line) => `  ${line}`) : []),
    '  return (',
    ...example.jsx.split('\n').map((line) => `    ${line}`),
    '  );',
    '}',
  ].join('\n');
  return {
    id,
    name,
    category,
    description,
    purpose: description,
    usage,
    importPath,
    code,
    anatomy,
    variants,
    docsUrl: `${docsBase}${story}--docs`,
    keywords: [id, category, ...keywords],
  };
}
const buttonImport = `import { Button } from '${packageName}/button';`;
const iconsImport = (names: string) => `import { ${names} } from '${packageName}/icons';`;
const stateOptions = '[{ value: "new", label: "New" }, { value: "triaged", label: "Triaged" }]';
const chartData =
  '[{ hour: "09:00", events: 18 }, { hour: "10:00", events: 32 }, { hour: "11:00", events: 24 }]';
const chartSeries = '[{ key: "events", label: "Events" }]';
const sizes = v('size', ['sm', 'md', 'lg'], 'md');
const statuses = v('status', ['new', 'triaged', 'in-progress', 'resolved', 'false-positive']);
const severities = v('severity', ['critical', 'high', 'medium', 'low', 'info']);
const confidence = v('confidence', ['high', 'medium', 'low']);

export const componentCatalogue: ComponentCatalogueEntry[] = [
  entry(
    'button',
    'Button',
    'Actions',
    'Make the next action clear without giving every action the same weight.',
    'Choose emphasis for hierarchy and intent for meaning. Loading preserves the label and prevents repeat activation.',
    ['Container', 'Leading icon', 'Label', 'Trailing icon or loading indicator'],
    {
      exports: 'Button',
      setup: 'const [enabled, setEnabled] = useState(false);',
      jsx: '<Button intent="function" onClick={() => setEnabled(!enabled)}>\n  {enabled ? "Disable rule" : "Enable rule"}\n</Button>',
    },
    'components-actions-button',
    [
      sizes,
      v('emphasis', ['primary', 'secondary', 'tertiary', 'ghost'], 'primary'),
      v('intent', ['default', 'function', 'destroy', 'ai'], 'default'),
    ],
  ),
  entry(
    'icon-button',
    'Icon button',
    'Actions',
    'Keep repeated toolbar actions compact while retaining an accessible name.',
    'Provide aria-label for every icon-only action. The optional tooltip repeats that label on hover or focus.',
    ['Button target', 'Icon', 'Accessible label', 'Tooltip'],
    {
      exports: 'IconButton',
      imports: [iconsImport('Check')],
      setup: 'const [reviewed, setReviewed] = useState(false);',
      jsx: '<IconButton aria-label={reviewed ? "Undo review" : "Mark reviewed"}\n  aria-pressed={reviewed} onClick={() => setReviewed(!reviewed)}>\n  <Check size={18} />\n</IconButton>',
    },
    'components-actions-iconbutton',
    [sizes, v('emphasis', ['primary', 'secondary', 'tertiary', 'ghost'])],
  ),
  entry(
    'button-group',
    'Button group',
    'Actions',
    'Keep related actions together in one compact row.',
    'Give the group an accessible label and compose ordinary Buttons. Selection state belongs to each action.',
    ['Labeled group', 'Adjacent buttons'],
    {
      exports: 'ButtonGroup',
      imports: [buttonImport],
      setup: 'const [period, setPeriod] = useState("Day");',
      jsx: '<ButtonGroup aria-label="Chart period">\n  {["Day", "Week", "Month"].map((value) => (\n    <Button key={value} emphasis={period === value ? "secondary" : "ghost"}\n      aria-pressed={period === value} onClick={() => setPeriod(value)}>{value}</Button>\n  ))}\n</ButtonGroup>',
    },
    'components-actions-buttongroup',
  ),
  entry(
    'copy-button',
    'Copy button',
    'Actions',
    'Copy an identifier or code fragment with visible confirmation.',
    'Pass the exact text to copy. Clipboard failures are reported; optional notifications use a mounted toaster.',
    ['Icon button', 'Copy / copied icon', 'Accessible feedback'],
    { exports: 'CopyButton', jsx: '<CopyButton text="ALR-1042" aria-label="Copy alert ID" />' },
    'components-actions-copybutton',
    [sizes],
  ),

  entry(
    'field',
    'Field',
    'Forms',
    'Connect a label, control, help text, and validation message.',
    'Wrap one compatible control. Field context composes its ID, required state, and description references automatically.',
    ['Label', 'Required or optional marker', 'Control slot', 'Help or error text'],
    {
      exports: 'Field',
      imports: [`import { TextInput } from '${packageName}/text-input';`],
      jsx: '<Field label="Rule name" required helpText="Use a name analysts can recognize.">\n  <TextInput placeholder="Suspicious PowerShell" />\n</Field>',
    },
    'components-forms-field',
    [v('state', ['default', 'required', 'optional', 'disabled', 'error'])],
  ),
  entry(
    'text-input',
    'Text input',
    'Forms',
    'Collect a short value with optional prefix, suffix, and clear action.',
    'Use label when standalone or compose with Field. value/onValueChange provide a controlled string value.',
    ['Label', 'Input shell', 'Prefix', 'Text control', 'Suffix or clear action'],
    {
      exports: 'TextInput',
      setup: 'const [name, setName] = useState("Suspicious PowerShell");',
      jsx: '<TextInput label="Rule name" value={name} onValueChange={setName} clearable />',
    },
    'components-forms-textinput',
    [sizes, v('state', ['default', 'disabled', 'invalid', 'readOnly'])],
  ),
  entry(
    'search-input',
    'Search input',
    'Forms',
    'Search large collections without firing work for every keystroke.',
    'onValueChange updates immediately; onSearch is debounced. Superseded callbacks are canceled when text changes.',
    ['Search icon', 'Query input', 'Clear action', 'Optional shortcut'],
    {
      exports: 'SearchInput',
      setup: 'const [query, setQuery] = useState("");',
      jsx: '<div>\n  <SearchInput label="Search alerts" onSearch={setQuery} debounceMs={250} />\n  <p role="status">{query ? `Searching for ${query}` : "All alerts"}</p>\n</div>',
    },
    'components-forms-searchinput',
    [sizes],
  ),
  entry(
    'textarea',
    'Textarea',
    'Forms',
    'Give notes and descriptions room to grow without losing context.',
    'Enable autoGrow with maxRows to bound the control. showCount can work with a native maxLength limit.',
    ['Label', 'Multiline control', 'Character count'],
    {
      exports: 'Textarea',
      jsx: '<Textarea label="Investigation note" autoGrow rows={3} maxRows={8}\n  maxLength={500} showCount placeholder="Describe the evidence…" />',
    },
    'components-forms-textarea',
    [
      v('autoGrow', ['false', 'true'], 'false'),
      v('state', ['default', 'disabled', 'invalid', 'readOnly']),
    ],
  ),
  entry(
    'checkbox',
    'Checkbox',
    'Forms',
    'Select independent options, including partially selected groups.',
    'checked accepts true, false, or indeterminate. Use the compact size for dense facets and table controls.',
    ['Checkbox indicator', 'Label', 'Optional description'],
    {
      exports: 'Checkbox',
      setup: 'const [checked, setChecked] = useState(false);',
      jsx: '<Checkbox label="Include resolved alerts" checked={checked}\n  onCheckedChange={(next) => setChecked(next === true)} />',
    },
    'components-forms-checkbox',
    [v('size', ['sm', 'md'], 'md'), v('checked', ['false', 'true', 'indeterminate'], 'false')],
  ),
  entry(
    'radio-group',
    'Radio group',
    'Forms',
    'Present a small set of mutually exclusive choices.',
    'Options can include descriptions and disabled choices. Arrow keys move through the group using native Radix behavior.',
    ['Group label', 'Radio indicator', 'Option label', 'Description'],
    {
      exports: 'RadioGroup',
      jsx: '<RadioGroup label="Rule mode" defaultValue="monitor" options={[\n  { value: "monitor", label: "Monitor", description: "Collect matches without notification" },\n  { value: "notify", label: "Notify", description: "Send matches to the alert queue" },\n]} />',
    },
    'components-forms-radiogroup',
    [v('orientation', ['vertical', 'horizontal'], 'vertical')],
  ),
  entry(
    'switch',
    'Switch',
    'Forms',
    'Turn a setting on or off with an immediate, visible state.',
    'Use checked/onCheckedChange for controlled settings and explain the effect with a description when needed.',
    ['Track', 'Thumb', 'Label', 'Description'],
    {
      exports: 'Switch',
      setup: 'const [enabled, setEnabled] = useState(true);',
      jsx: '<Switch label="Enable detection" description="Evaluate incoming process events"\n  checked={enabled} onCheckedChange={setEnabled} />',
    },
    'components-forms-switch',
    [v('size', ['sm', 'md'], 'md')],
  ),
  entry(
    'select',
    'Select',
    'Forms',
    'Choose one value from a labeled list of options.',
    'Options support icons, descriptions, groups, and disabled states. Use Field for shared validation text.',
    ['Trigger', 'Selected value', 'Chevron', 'Option group', 'Option indicator'],
    {
      exports: 'Select',
      setup: 'const [status, setStatus] = useState("new");',
      jsx: `<Select label="Alert status" value={status} onValueChange={setStatus}\n  options={${stateOptions}} />`,
    },
    'components-forms-select',
    [sizes, v('state', ['default', 'disabled', 'invalid', 'empty'])],
  ),
  entry(
    'multi-combobox',
    'Multi combobox',
    'Forms',
    'Find and select several values without crowding the form.',
    'Selected values become removable chips; maxVisible bounds them. Grouped options, loading, select-all, and clear are supported.',
    [
      'Trigger',
      'Selected chips',
      'Overflow count',
      'Search',
      'Grouped options',
      'Selection toolbar',
    ],
    {
      exports: 'MultiCombobox',
      setup: 'const [sources, setSources] = useState<string[]>(["edr"]);',
      jsx: '<MultiCombobox label="Sources" value={sources} onValueChange={setSources}\n  options={[{ value: "edr", label: "Endpoint detection", group: "Security" },\n    { value: "identity", label: "Identity", group: "Security" },\n    { value: "dns", label: "DNS", group: "Network" }]} />',
    },
    'components-forms-multicombobox',
    [v('state', ['default', 'loading', 'disabled', 'invalid', 'empty'])],
  ),
  entry(
    'slider',
    'Slider',
    'Forms',
    'Adjust a numeric value or bounded range with direct feedback.',
    'Values are arrays: one item for a single thumb, two for a range. Give each thumb a label when the meaning differs.',
    ['Label', 'Value display', 'Track', 'Range', 'Thumbs'],
    {
      exports: 'Slider',
      setup: 'const [range, setRange] = useState([20, 80]);',
      jsx: '<Slider label="Confidence range" value={range} onValueChange={setRange}\n  min={0} max={100} step={5} thumbLabels={["Minimum confidence", "Maximum confidence"]}\n  formatValue={(value) => `${value}%`} />',
    },
    'components-forms-slider',
    [v('orientation', ['horizontal', 'vertical'], 'horizontal')],
  ),
  entry(
    'date-picker',
    'Date picker',
    'Forms',
    'Choose a calendar date with keyboard navigation and clear feedback.',
    'Uses Date values and supports Field composition. The calendar opens in a collision-aware popover.',
    ['Labeled trigger', 'Month navigation', 'Weekday labels', 'Day grid'],
    {
      exports: 'DatePicker',
      setup: 'const [date, setDate] = useState<Date | undefined>();',
      jsx: '<DatePicker label="Review date" value={date} onValueChange={setDate} />',
    },
    'components-forms-datepicker',
    [v('state', ['default', 'disabled', 'invalid'])],
  ),
  entry(
    'time-range-picker',
    'Time range picker',
    'Forms',
    'Move between relative monitoring windows and precise UTC ranges.',
    'Relative values use a preset; absolute values use ISO from/to strings. Both forms share the public TimeRange type.',
    ['Range trigger', 'Preset list', 'Calendar', 'Time inputs', 'Apply action'],
    {
      exports: 'TimeRangePicker',
      imports: [`import type { TimeRange } from '${packageName}/time-range';`],
      setup: 'const [range, setRange] = useState<TimeRange>({ mode: "relative", preset: "24h" });',
      jsx: '<TimeRangePicker label="Investigation period" value={range} onValueChange={setRange} />',
    },
    'components-forms-timerangepicker',
    [v('mode', ['relative', 'absolute']), v('preset', ['15m', '1h', '24h', '7d', '30d'])],
  ),
  entry(
    'tree-view',
    'Tree view',
    'Forms',
    'Select nested scopes while keeping parent and child state consistent.',
    'Selection stores leaf IDs; parent checked and mixed states are derived. Arrow keys navigate, Space toggles, and disabled branches are preserved.',
    [
      'Tree item',
      'Disclosure control',
      'Tri-state checkbox',
      'Icon',
      'Label and count',
      'Nested branch',
    ],
    {
      exports: 'TreeView',
      jsx: '<TreeView label="Detection scope" defaultExpandedIds={["production"]}\n  items={[{ id: "production", label: "Production", children: [\n    { id: "endpoints", label: "Endpoints", count: 42 },\n    { id: "servers", label: "Servers", count: 16 },\n  ] }]} />',
    },
    'components-forms-treeview',
  ),

  entry(
    'breadcrumb',
    'Breadcrumb',
    'Navigation',
    'Keep the current location visible within a deeper workspace.',
    'Pass links or navigation callbacks for ancestors. The final item is the current page.',
    ['Navigation landmark', 'Ancestor links', 'Separators', 'Current page'],
    {
      exports: 'Breadcrumb',
      jsx: '<Breadcrumb items={[{ label: "Workspace", href: "/" },\n  { label: "Detections", href: "/detections" }, { label: "Rule details" }]} />',
    },
    'components-navigation-breadcrumb',
  ),
  entry(
    'tabs',
    'Tabs',
    'Navigation',
    'Switch related views without leaving the current task.',
    'Items pair labels with panels. Use sharedContent when one persistent workspace must keep its internal state across tabs.',
    ['Tab list', 'Active indicator', 'Optional count', 'Labeled panel'],
    {
      exports: 'Tabs',
      jsx: '<Tabs label="Investigation views" defaultValue="events" items={[\n  { value: "events", label: "Events", count: 12, content: <p>12 related process events</p> },\n  { value: "notes", label: "Notes", content: <p>No analyst notes yet.</p> },\n]} />',
    },
    'components-navigation-tabs',
    [
      v('variant', ['line', 'pill'], 'line'),
      v('orientation', ['horizontal', 'vertical'], 'horizontal'),
    ],
  ),
  entry(
    'side-nav',
    'Side navigation',
    'Navigation',
    'Organize a workspace into stable destinations and nested groups.',
    'Control activeId with onNavigate. The rail can collapse without losing item labels or keyboard access.',
    [
      'Workspace identity',
      'Search action',
      'Section label',
      'Navigation item',
      'Nested group',
      'Footer',
    ],
    {
      exports: 'SideNav',
      imports: [iconsImport('Shield, FileCode2')],
      setup: 'const [active, setActive] = useState("alerts");',
      jsx: '<SideNav activeId={active} onNavigate={setActive}\n  sections={[{ label: "Workspace", items: [\n    { id: "alerts", label: "Alerts", icon: <Shield size={17} />, count: 12 },\n    { id: "rules", label: "Rules", icon: <FileCode2 size={17} /> },\n  ] }]} />',
    },
    'components-navigation-sidenav',
    [v('collapsed', ['false', 'true'], 'false')],
  ),
  entry(
    'pagination',
    'Pagination',
    'Navigation',
    'Navigate a large result set with clear page and record counts.',
    'page is one-based. Pass total records and pageSize; add onPageSizeChange to expose a size selector.',
    ['Record range', 'Page-size selector', 'Previous / next actions', 'Page numbers'],
    {
      exports: 'Pagination',
      setup: 'const [page, setPage] = useState(1);',
      jsx: '<Pagination page={page} onPageChange={setPage} pageSize={25} total={150} noun="alerts" />',
    },
    'components-navigation-pagination',
  ),
  entry(
    'stepper',
    'Stepper',
    'Navigation',
    'Show progress through a sequence without hiding completed steps.',
    'currentStep is zero-based. Optional onStepChange enables navigation to the current or completed steps.',
    ['Ordered steps', 'State indicator', 'Title', 'Description', 'Connector'],
    {
      exports: 'Stepper',
      setup: 'const [step, setStep] = useState(1);',
      jsx: '<Stepper currentStep={step} onStepChange={setStep} steps={[\n  { id: "define", title: "Define" }, { id: "test", title: "Test" },\n  { id: "review", title: "Review" },\n]} />',
    },
    'components-navigation-stepper',
    [
      v('orientation', ['horizontal', 'vertical'], 'horizontal'),
      v('step state', ['upcoming', 'current', 'complete', 'error']),
    ],
  ),
  entry(
    'command-palette',
    'Command palette',
    'Navigation',
    'Reach workspace actions through one searchable keyboard surface.',
    'Actions carry labels, groups, keywords, and callbacks. A controlled open state supports an explicit launcher alongside the optional shortcut.',
    ['Dialog', 'Search field', 'Command groups', 'Command item', 'Shortcut hints'],
    {
      exports: 'CommandPalette',
      imports: [buttonImport],
      setup:
        'const [open, setOpen] = useState(false);\nconst [result, setResult] = useState("No command run");',
      jsx: '<>\n  <Button onClick={() => setOpen(true)}>Search commands</Button>\n  <CommandPalette open={open} onOpenChange={setOpen} actions={[\n    { id: "review", label: "Review selected alert", group: "Investigation",\n      onSelect: () => setResult("Alert opened for review") },\n  ]} />\n  <p role="status">{result}</p>\n</>',
    },
    'components-navigation-commandpalette',
  ),

  entry(
    'avatar',
    'Avatar',
    'Data display',
    'Identify an analyst with a photo, initials, or presence indicator.',
    'Always supply name for the accessible label and initials fallback. AvatarGroup limits a collection with an overflow count.',
    ['Image or initials', 'Presence indicator', 'Optional group overflow'],
    {
      exports: 'Avatar, AvatarGroup',
      jsx: '<div style={{ display: "flex", gap: 16, alignItems: "center" }}>\n  <Avatar name="Alex Morgan" status="online" />\n  <AvatarGroup label="Assigned analysts" max={2} avatars={[\n    { name: "Alex Morgan" }, { name: "Sam Rivera" }, { name: "Jordan Lee" },\n  ]} />\n</div>',
    },
    'components-people-avatar',
    [sizes, v('status', ['online', 'away', 'busy', 'offline'])],
  ),
  entry(
    'severity-badge',
    'Severity badge',
    'Data display',
    'Distinguish risk levels with a consistent label, icon, and color.',
    'Use the shared severity vocabulary. Compact badges reduce decoration while retaining the severity label.',
    ['Severity icon', 'Text label', 'Semantic background'],
    { exports: 'SeverityBadge', jsx: '<SeverityBadge severity="high" />' },
    'components-tags-severitybadge',
    [severities, v('compact', ['false', 'true'], 'false')],
  ),
  entry(
    'status-badge',
    'Status badge',
    'Data display',
    'Show the workflow state independently of its severity.',
    'StatusBadge provides a compact labeled surface; StatusDot uses the same status mapping with a lighter footprint.',
    ['Status marker', 'Workflow label'],
    {
      exports: 'StatusBadge, StatusDot',
      jsx: '<div style={{ display: "flex", gap: 16 }}>\n  <StatusBadge status="in-progress" />\n  <StatusDot status="triaged" />\n</div>',
    },
    'components-tags-statusbadge',
    [statuses],
  ),
  entry(
    'count-badge',
    'Count badge',
    'Data display',
    'Show a bounded count beside a tab, queue, or navigation item.',
    'Use label to explain the count to assistive technology. Values above max display as an overflow count.',
    ['Numeric value', 'Optional overflow suffix', 'Accessible count description'],
    { exports: 'CountBadge', jsx: '<CountBadge count={150} max={99} label="150 open alerts" />' },
    'components-tags-countbadge',
    [v('variant', ['default', 'inverted'], 'default')],
  ),
  entry(
    'tag',
    'Tag',
    'Data display',
    'Represent a label, removable filter, or lightweight selection.',
    'Choose the variant that matches behavior. Removable and interactive tags provide their own keyboard-accessible controls.',
    ['Label', 'Optional count', 'Selection state', 'Remove action'],
    {
      exports: 'Tag',
      setup: 'const [visible, setVisible] = useState(true);',
      jsx: '<div>\n  {visible ? <Tag variant="removable" onRemove={() => setVisible(false)}>Production</Tag>\n    : <button type="button" onClick={() => setVisible(true)}>Restore tag</button>}\n</div>',
    },
    'components-tags-tag',
    [
      v('variant', ['static', 'removable', 'interactive', 'counter'], 'static'),
      v('size', ['sm', 'md'], 'md'),
    ],
  ),
  entry(
    'kbd',
    'Keyboard hint',
    'Data display',
    'Make keyboard shortcuts recognizable beside their actions.',
    'Kbd is a presentational keyboard key; bind the actual shortcut in the owning interaction.',
    ['Key label', 'Keycap surface'],
    { exports: 'Kbd', jsx: '<span>Open search <Kbd>⌘</Kbd> <Kbd>K</Kbd></span>' },
    'components-tags-kbd',
    [v('size', ['sm', 'md'], 'sm')],
  ),
  entry(
    'relative-time',
    'Relative time',
    'Data display',
    'Keep recent activity readable while retaining the exact timestamp.',
    'Pass now for reproducible historical views. The exact date remains available in the time element and tooltip.',
    ['Relative label', 'Machine-readable timestamp', 'Exact-time tooltip'],
    {
      exports: 'RelativeTime',
      jsx: '<RelativeTime value="2026-10-06T09:15:00Z" now={Date.parse("2026-10-06T09:30:00Z")}\n  timeZone="UTC" />',
    },
    'components-data-relativetime',
    [v('compact', ['false', 'true'], 'false')],
  ),
  entry(
    'timeline',
    'Timeline',
    'Data display',
    'Read an investigation as an ordered sequence of evidence and decisions.',
    'Each event carries a timestamp, title, and optional actor, description, or actions. Event types determine the default marker.',
    ['Event marker', 'Connector', 'Title', 'Timestamp', 'Actor and description'],
    {
      exports: 'Timeline',
      jsx: '<Timeline label="Alert activity" now={Date.parse("2026-10-06T09:30:00Z")} items={[\n  { id: "1", type: "detection", title: "Alert detected", timestamp: "2026-10-06T09:15:00Z" },\n  { id: "2", type: "assignment", title: "Assigned to Alex", timestamp: "2026-10-06T09:20:00Z", actor: "Sam Rivera" },\n]} />',
    },
    'components-data-timeline',
    [v('event type', ['detection', 'assignment', 'status', 'note', 'ai', 'event'])],
  ),
  entry(
    'json-viewer',
    'JSON viewer',
    'Data display',
    'Inspect structured event data without flattening its hierarchy.',
    'Accepts any JSON-like value. Expand nested paths, search content, and copy values or paths without editing the source.',
    ['Search toolbar', 'Tree disclosure', 'Key', 'Typed value', 'Copy actions'],
    {
      exports: 'JsonViewer',
      jsx: '<JsonViewer label="Process event" defaultExpandedDepth={2}\n  value={{ host: "WS-ATH-114", process: { name: "powershell.exe", pid: 4812 }, tags: ["execution"] }} />',
    },
    'components-data-jsonviewer',
  ),
  entry(
    'expandable-text',
    'Expandable text',
    'Data display',
    'Keep a long description compact until the reader asks for more.',
    'collapsedLines sets the preview height. The toggle appears only when the text actually overflows; controlled expansion is optional.',
    ['Text block', 'Line clamp', 'Read more / show less control'],
    {
      exports: 'ExpandableText',
      jsx: '<ExpandableText collapsedLines={2}>\n  {"The process launched an encoded command shortly after the document opened. " +\n    "Review the parent process, command line, and related network events before changing the alert status. ".repeat(3)}\n</ExpandableText>',
    },
    'components-content-expandabletext',
  ),
  entry(
    'list',
    'List',
    'Data display',
    'Lay out compact records with consistent space for context and actions.',
    'Compose ListItem with title, description, meta, and action slots. Selection is opt-in and controlled per item.',
    ['List container', 'Icon or avatar', 'Title and description', 'Metadata', 'Actions'],
    {
      exports: 'List, ListItem',
      jsx: '<List density="compact" divided>\n  <ListItem title="Encoded PowerShell" description="WS-ATH-114" meta="12 events" />\n  <ListItem title="Unusual sign-in" description="alex@example.com" meta="3 events" />\n</List>',
    },
    'components-lists-list',
    [v('density', ['compact', 'default', 'comfortable'], 'default')],
  ),

  entry(
    'data-grid',
    'Data grid',
    'Data grid',
    'Work through dense records with sorting, selection, expansion, and column controls.',
    'Supply stable row IDs and column definitions. Pagination and virtualization are optional; trailing Actions stay compact while the last visible data column fills spare width.',
    [
      'Toolbar slot',
      'Sortable headers',
      'Resizable columns',
      'Selection',
      'Rows',
      'Expanded detail',
      'Pagination',
    ],
    {
      exports: 'DataGrid',
      jsx: '<DataGrid label="Alerts" getRowId={(row) => row.id}\n  data={[{ id: "ALR-1042", title: "Encoded PowerShell", events: 12 },\n    { id: "ALR-1043", title: "Unusual sign-in", events: 3 }]}\n  columns={[{ accessorKey: "title", header: "Alert" }, { accessorKey: "events", header: "Events" }]}\n  enableSelection density="compact" />',
    },
    'components-data-datagrid',
    [
      v('density', ['compact', 'default', 'comfortable'], 'default'),
      v('pagination', ['true', 'false']),
      v('virtualize', ['false', 'true']),
    ],
  ),
  entry(
    'bulk-actions-bar',
    'Bulk actions bar',
    'Data grid',
    'Act on a selection without repeating the same change row by row.',
    'Callbacks can return promises; pending actions are guarded and failures stay visible. A zero count hides the bar.',
    ['Selected count', 'Assign menu', 'Status menu', 'AI action', 'Clear selection'],
    {
      exports: 'BulkActionsBar',
      setup: 'const [count, setCount] = useState(3);\nconst [result, setResult] = useState("");',
      jsx: '<>\n  <BulkActionsBar position="inline" selectedCount={count}\n    analysts={[{ id: "alex", name: "Alex Morgan" }]}\n    onAssign={(id) => setResult(id ? `Assigned to ${id}` : "Assignee removed")}\n    onStatusChange={(status) => setResult(`Status changed to ${status}`)}\n    onSummarize={() => setResult("Connect your summarization workflow here")}\n    onClear={() => setCount(0)} />\n  <p role="status">{result}</p>\n</>',
    },
    'components-data-grid-bulk-actions-bar',
    [v('position', ['fixed', 'inline'], 'fixed')],
  ),
  entry(
    'data-grid-cells',
    'Data grid cells',
    'Data grid',
    'Use a consistent vocabulary for entities, status, timestamps, and row actions.',
    'Cell components are independently exported from one subpath and compose inside ordinary column renderers. EntityCell supports user, host, and IP records.',
    ['Entity icon or avatar', 'Primary value', 'Secondary detail', 'Semantic metadata'],
    {
      exports: 'EntityCell, SeverityCell, StatusCell',
      subpath: 'data-grid-cells',
      jsx: '<div style={{ display: "flex", gap: 16, alignItems: "center", flexWrap: "wrap" }}>\n  <EntityCell entity={{ type: "host", name: "WS-ATH-114", detail: "Windows endpoint" }} />\n  <SeverityCell severity="high" /><StatusCell status="new" />\n</div>',
    },
    'components-data-grid-cells',
    [v('entity type', ['user', 'host', 'ip'])],
  ),
  entry(
    'severity-cell',
    'Severity cell',
    'Data grid',
    'Carry the shared severity language into a dense row.',
    'This adapter renders SeverityBadge and accepts the same compact option.',
    ['Severity badge', 'Risk label'],
    {
      exports: 'SeverityCell',
      subpath: 'data-grid-cells',
      jsx: '<SeverityCell severity="critical" compact />',
    },
    'components-data-grid-severity-cell',
    [severities],
  ),
  entry(
    'status-cell',
    'Status cell',
    'Data grid',
    'Keep workflow labels consistent across tables and detail views.',
    'This adapter uses StatusBadge and the shared AlertStatus vocabulary.',
    ['Status marker', 'Status label'],
    { exports: 'StatusCell', subpath: 'data-grid-cells', jsx: '<StatusCell status="triaged" />' },
    'components-data-grid-status-cell',
    [statuses],
  ),
  entry(
    'time-cell',
    'Time cell',
    'Data grid',
    'Fit readable timestamps into compact columns.',
    'Uses the compact RelativeTime format with an exact-time tooltip. Supply now when rendering historical records.',
    ['Relative timestamp', 'Exact-time tooltip'],
    {
      exports: 'TimeCell',
      subpath: 'data-grid-cells',
      jsx: '<TimeCell value="2026-10-06T09:15:00Z" now={Date.parse("2026-10-06T09:30:00Z")} />',
    },
    'components-data-grid-time-cell',
  ),
  entry(
    'number-cell',
    'Number cell',
    'Data grid',
    'Format comparable numeric values consistently within a column.',
    'Accepts Intl.NumberFormat options and a locale. Non-finite values render a dash.',
    ['Formatted value', 'Tabular alignment'],
    {
      exports: 'NumberCell',
      subpath: 'data-grid-cells',
      jsx: '<NumberCell value={12480} locale="en-GB" format={{ notation: "compact", maximumFractionDigits: 1 }} />',
    },
    'components-data-grid-number-cell',
  ),
  entry(
    'tags-cell',
    'Tags cell',
    'Data grid',
    'Show useful labels without letting long tag lists dominate the row.',
    'maxVisible bounds the visible tags. Remaining values are available through a focusable overflow count.',
    ['Visible tags', 'Overflow count', 'Overflow tooltip'],
    {
      exports: 'TagsCell',
      subpath: 'data-grid-cells',
      jsx: '<TagsCell tags={["Execution", "PowerShell", "Production", "Endpoint"]} maxVisible={2} />',
    },
    'components-data-grid-tags-cell',
  ),
  entry(
    'sparkline-cell',
    'Sparkline cell',
    'Data grid',
    'Compare recent activity directly alongside a record.',
    'A dense adapter for Sparkline. Give meaningful trends a label that includes the measurement and period.',
    ['Trend graphic', 'Accessible summary'],
    {
      exports: 'SparklineCell',
      subpath: 'data-grid-cells',
      jsx: '<SparklineCell data={[2, 4, 3, 8, 5, 12, 7]} variant="area" label="Events over seven hours" />',
    },
    'components-data-grid-sparkline-cell',
    [v('variant', ['line', 'area', 'bar'], 'line')],
  ),
  entry(
    'actions-cell',
    'Actions cell',
    'Data grid',
    'Keep common row actions close and less common actions in an overflow menu.',
    'Each action has an accessible label and callback. Row click propagation is stopped so actions do not accidentally open the record.',
    ['Visible action buttons', 'Overflow menu', 'Action labels'],
    {
      exports: 'ActionsCell',
      subpath: 'data-grid-cells',
      imports: [iconsImport('Check')],
      setup: 'const [reviewed, setReviewed] = useState(false);',
      jsx: '<>\n  <ActionsCell label="Alert actions" actions={[{ id: "review",\n    label: reviewed ? "Undo review" : "Mark reviewed", icon: <Check size={15} />,\n    onClick: () => setReviewed(!reviewed) }]} />\n  <span role="status">{reviewed ? "Reviewed" : "Awaiting review"}</span>\n</>',
    },
    'components-data-grid-actions-cell',
  ),
  entry(
    'ai-verdict-cell',
    'AI verdict cell',
    'Data grid',
    'Distinguish a suggested verdict from an analyst decision.',
    'confidence is a normalized number from 0 to 1. The tooltip exposes its percentage and reminds readers to review the evidence.',
    ['AI marker', 'Suggested verdict', 'Confidence tooltip'],
    {
      exports: 'AiVerdictCell',
      subpath: 'data-grid-cells',
      jsx: '<AiVerdictCell verdict="Investigate" confidence={0.86} />',
    },
    'components-data-grid-ai-verdict-cell',
  ),
  entry(
    'expand-cell',
    'Expand cell',
    'Data grid',
    'Reveal supporting detail beneath a row with a clear disclosure control.',
    'Control expanded and render the associated detail in the owning row. count can indicate related records.',
    ['Disclosure chevron', 'Accessible label', 'Optional record count'],
    {
      exports: 'ExpandCell',
      subpath: 'data-grid-cells',
      setup: 'const [expanded, setExpanded] = useState(false);',
      jsx: '<>\n  <ExpandCell label="Related events" expanded={expanded} onExpandedChange={setExpanded} count={6} />\n  {expanded && <p>Six related process events are available for review.</p>}\n</>',
    },
    'components-data-grid-expand-cell',
  ),

  entry(
    'chart-container',
    'Chart container',
    'Charts',
    'Give every visualization a consistent title, legend, and state treatment.',
    'Wrap custom chart content or use the chart components that already compose this frame. Loading, empty, and error states share the same layout.',
    ['Title and description', 'Action slot', 'Plot region', 'Legend', 'Footer or data table'],
    {
      exports: 'ChartContainer',
      subpath: 'charts',
      jsx: '<ChartContainer title="Event volume" description="Last 24 hours" height={180} empty\n  emptyTitle="No events in this period" />',
    },
    'components-charts-chart-container',
    [v('state', ['ready', 'loading', 'empty', 'error'])],
  ),
  ...(['line', 'area', 'bar'] as const).map((kind) => {
    const component = `${kind[0].toUpperCase()}${kind.slice(1)}Chart`;
    const descriptions = {
      line: 'Compare changes over time without obscuring the individual series.',
      area: 'Show how a time series accumulates or changes in volume.',
      bar: 'Compare quantities across buckets with grouped or stacked series.',
    };
    return entry(
      `${kind}-chart`,
      `${kind[0].toUpperCase()}${kind.slice(1)} chart`,
      'Charts',
      descriptions[kind],
      'Provide data and named series; xKey selects the category field. Legends can toggle series, and the optional data table offers a text representation.',
      ['Chart frame', 'Axes', 'Series', 'Tooltip', 'Interactive legend', 'Optional data table'],
      {
        exports: component,
        subpath: 'charts',
        jsx: `<${component} title="Event volume" xKey="hour"\n  data={${chartData}}\n  series={${chartSeries}} height={240} showDataTable />`,
      },
      `components-charts-${kind}-chart`,
      [
        v('stacked', ['false', 'true'], 'false'),
        v('state', ['ready', 'loading', 'empty', 'error']),
      ],
    );
  }),
  entry(
    'donut-chart',
    'Donut chart',
    'Charts',
    'Show the distribution of a total across a small set of categories.',
    'Each datum has name and value. Keep categories few enough for the legend to remain useful and expose the data table when exact values matter.',
    ['Chart frame', 'Segments', 'Center total', 'Legend', 'Data table'],
    {
      exports: 'DonutChart',
      subpath: 'charts',
      jsx: '<DonutChart title="Alert sources" data={[{ name: "EDR", value: 64 },\n  { name: "Identity", value: 28 }, { name: "DNS", value: 12 }]}\n  totalLabel="alerts" height={240} showDataTable />',
    },
    'components-charts-donut-chart',
  ),
  entry(
    'event-histogram',
    'Event histogram',
    'Charts',
    'Read event volume by severity and narrow the investigation period.',
    'SeverityBucket data includes a timestamp, display label, five severity counts, and a total. An optional brush uses the same TimeRange contract as the picker.',
    ['Time buckets', 'Severity stacks', 'Legend', 'Optional range brush'],
    {
      exports: 'EventHistogram',
      jsx: '<EventHistogram title="Events by severity" data={[\n  { time: "2026-10-06T09:00:00Z", label: "09:00", critical: 1, high: 3, medium: 8, low: 4, info: 2, total: 18 },\n  { time: "2026-10-06T09:30:00Z", label: "09:30", critical: 2, high: 6, medium: 12, low: 8, info: 4, total: 32 },\n]} />',
    },
    'components-charts-event-histogram',
    [v('brush', ['false', 'true'], 'false')],
  ),
  entry(
    'metric-card',
    'Metric card',
    'Charts',
    'Summarize one important number with its context and recent trend.',
    'Provide a label and value; add unit, delta, and sparkline when they help interpret the number. trendIsPositive controls the meaning of the change.',
    ['Metric label', 'Value and unit', 'Delta', 'Sparkline'],
    {
      exports: 'MetricCard',
      jsx: '<MetricCard label="Open alerts" value={150} delta={-12} deltaLabel="vs. previous day"\n  trendIsPositive sparkline={[184, 176, 162, 170, 158, 154, 150]}\n  sparklineLabel="Open alerts over seven days" />',
    },
    'components-charts-metric-card',
    [v('sparklineVariant', ['line', 'area', 'bar'])],
  ),
  entry(
    'sparkline',
    'Sparkline',
    'Charts',
    'Show the shape of a small time series where a full chart would be too heavy.',
    'Pass numeric data and an accessible label. This lightweight SVG primitive fits cards, rows, and compact summaries.',
    ['Trend path or bars', 'Optional area fill', 'Accessible label'],
    {
      exports: 'Sparkline',
      jsx: '<Sparkline data={[3, 5, 4, 9, 6, 12, 8]} variant="area" width={180} height={48}\n  label="Events over seven hours, peaking at twelve" />',
    },
    'components-charts-sparkline',
    [
      v('variant', ['line', 'area', 'bar'], 'line'),
      v('intent', ['function', 'ai', 'success', 'warning', 'destroy'], 'function'),
    ],
  ),

  entry(
    'code-editor',
    'Code editor',
    'Code',
    'Edit YAML or JSON within the same visual language as the surrounding form.',
    'CodeMirror provides line numbers, folding, syntax colors, and cursor status. Tab exits the editor so keyboard users are not trapped.',
    ['Editor gutter', 'Syntax-highlighted content', 'Fold controls', 'Status bar'],
    {
      exports: 'CodeEditor',
      setup: 'const [code, setCode] = useState("title: Suspicious PowerShell\\nlevel: high\\n");',
      jsx: '<CodeEditor label="Detection rule YAML" language="yaml" value={code}\n  onValueChange={setCode} minHeight={180} maxHeight={360} />',
    },
    'components-code-codeeditor',
    [v('language', ['yaml', 'json'], 'yaml'), v('readOnly', ['false', 'true'], 'false')],
  ),
  entry(
    'yaml-presenter',
    'YAML presenter',
    'Code',
    'Present a configuration file with context and targeted highlights.',
    'A read-only code surface with a filename header and copy action. highlightedLines marks inclusive line ranges.',
    ['Filename', 'Copy action', 'Line numbers', 'Highlighted source'],
    {
      exports: 'YamlPresenter',
      jsx: '<YamlPresenter filename="detection.yml" value={"title: Suspicious PowerShell\\nlevel: high\\n"}\n  highlightedLines={[{ from: 2, to: 2 }]} />',
    },
    'components-code-yamlpresenter',
  ),
  entry(
    'diff-view',
    'Diff view',
    'Code',
    'Review the exact changes between two versions of a configuration.',
    'Choose split or unified presentation. original and modified remain separate; use onModifiedChange only when the proposed side is editable.',
    ['Version labels', 'Mode control', 'Removed lines', 'Added lines', 'Unchanged context'],
    {
      exports: 'DiffView',
      jsx: '<DiffView label="Rule changes" language="yaml"\n  original={"title: Suspicious PowerShell\\nlevel: medium\\n"}\n  modified={"title: Suspicious PowerShell\\nlevel: high\\n"}\n  defaultMode="unified" readOnly />',
    },
    'components-code-diffview',
    [v('mode', ['split', 'unified'], 'split'), v('modifiedIntent', ['default', 'ai'], 'default')],
  ),

  entry(
    'modal',
    'Modal',
    'Overlays',
    'Focus attention on a bounded task without losing the original workspace.',
    'A labeled modal dialog with focus containment and return. Header and footer are optional; ModalClose composes an explicit close action.',
    ['Scrim', 'Dialog surface', 'Title and close action', 'Scrollable body', 'Optional footer'],
    {
      exports: 'Modal, ModalClose',
      imports: [buttonImport],
      jsx: '<Modal title="Review rule" description="Confirm the rule before enabling it."\n  size="regular" trigger={<Button>Review rule</Button>}\n  footer={<ModalClose asChild><Button intent="function">Done</Button></ModalClose>}>\n  <p>This rule monitors encoded PowerShell execution.</p>\n</Modal>',
    },
    'components-overlays-modal',
    [
      v('size', ['small', 'regular', 'large'], 'regular'),
      v('showHeader', ['true', 'false'], 'true'),
    ],
  ),
  entry(
    'popover',
    'Popover',
    'Overlays',
    'Add a small contextual form or explanation beside its trigger.',
    'Header and footer stay outside the scrollable body. Choose regular or tight density; popovers intentionally omit divider lines.',
    ['Trigger', 'Floating surface', 'Optional title', 'Body', 'Optional footer and close action'],
    {
      exports: 'Popover, PopoverClose',
      imports: [buttonImport],
      jsx: '<Popover title="Retention policy" trigger={<Button emphasis="secondary">Policy details</Button>}\n  footer={<PopoverClose asChild><Button size="sm">Understood</Button></PopoverClose>}>\n  <p>Events are retained for 30 days.</p>\n</Popover>',
    },
    'components-overlays-popover',
    [
      v('density', ['regular', 'tight'], 'regular'),
      v('side', ['top', 'right', 'bottom', 'left'], 'bottom'),
    ],
  ),
  entry(
    'side-sheet',
    'Side sheet',
    'Overlays',
    'Open record details while preserving the queue behind them.',
    'Header actions align with the title and close button. Footer actions and previous/next navigation support longer review workflows; docked mode is optional.',
    [
      'Sheet surface',
      'Title and close action',
      'Header actions',
      'Scrollable body',
      'Footer',
      'Record navigation',
    ],
    {
      exports: 'SideSheet, SideSheetSection, SideSheetField',
      imports: [buttonImport],
      jsx: '<SideSheet title="ALR-1042" description="Encoded PowerShell"\n  trigger={<Button>Open alert</Button>} footer={<p>Review the evidence before resolving.</p>}>\n  <SideSheetSection title="Evidence">\n    <SideSheetField label="Host">WS-ATH-114</SideSheetField>\n    <SideSheetField label="Process">powershell.exe</SideSheetField>\n  </SideSheetSection>\n</SideSheet>',
    },
    'components-overlays-sidesheet',
    [v('size', ['sm', 'md', 'lg'], 'md'), v('docked', ['false', 'true'], 'false')],
  ),
  entry(
    'bottom-sheet',
    'Bottom sheet',
    'Overlays',
    'Keep supporting records visible beneath a working area.',
    'This nonmodal, resizable panel belongs inside a bounded flex-column workspace. It preserves a minimum workspace height and supports keyboard resizing.',
    [
      'Resize handle',
      'Title and close action',
      'Header actions',
      'Scrollable body',
      'Optional footer',
    ],
    {
      exports: 'BottomSheet',
      imports: [buttonImport],
      setup: 'const [open, setOpen] = useState(false);',
      jsx: '<div style={{ height: 480, display: "flex", flexDirection: "column" }}>\n  <div style={{ flex: 1, minHeight: 0 }}><Button onClick={() => setOpen(true)}>Open events</Button></div>\n  <BottomSheet title="Related events" open={open} onOpenChange={setOpen} defaultHeight={220}>\n    <p>Six process events match this detection.</p>\n  </BottomSheet>\n</div>',
    },
    'components-overlays-bottomsheet',
  ),
  entry(
    'tooltip',
    'Tooltip',
    'Overlays',
    'Explain a compact control without adding permanent visual noise.',
    'Use short supporting text; important instructions belong in visible content. RichTooltip adds a title, description, and optional shortcut.',
    ['Trigger', 'Label or rich content', 'Directional arrow'],
    {
      exports: 'Tooltip',
      imports: [buttonImport],
      jsx: '<Tooltip content="Export the visible rows as a CSV file">\n  <Button emphasis="secondary">Export</Button>\n</Tooltip>',
    },
    'components-overlays-tooltip',
    [
      v('variant', ['default', 'inverted'], 'default'),
      v('side', ['top', 'right', 'bottom', 'left'], 'top'),
    ],
  ),
  entry(
    'dropdown-menu',
    'Dropdown menu',
    'Overlays',
    'Group secondary actions behind a predictable menu trigger.',
    'Entries support actions, checkboxes, radio groups, nested groups, and submenus. Radix supplies roving focus and dismissal behavior.',
    ['Trigger', 'Menu surface', 'Labeled groups', 'Menu items', 'Submenu', 'Shortcut hints'],
    {
      exports: 'DropdownMenu',
      imports: [buttonImport],
      setup: 'const [result, setResult] = useState("No action selected");',
      jsx: '<>\n  <DropdownMenu trigger={<Button emphasis="secondary">Alert actions</Button>} items={[\n    { id: "review", label: "Mark reviewed", onSelect: () => setResult("Marked reviewed") },\n    { id: "archive", label: "Archive", onSelect: () => setResult("Archived") },\n  ]} />\n  <p role="status">{result}</p>\n</>',
    },
    'components-lists-dropdownmenu',
  ),
  entry(
    'context-menu',
    'Context menu',
    'Overlays',
    'Offer record actions at the point of interaction.',
    'Wrap a focusable target so the menu is also reachable with the keyboard context-menu shortcut. Entry shapes match DropdownMenu.',
    ['Context target', 'Menu surface', 'Action items', 'Nested groups'],
    {
      exports: 'ContextMenu',
      setup: 'const [reviewed, setReviewed] = useState(false);',
      jsx: '<ContextMenu items={[{ id: "review", label: "Mark reviewed", onSelect: () => setReviewed(true) }]}>\n  <button type="button">{reviewed ? "Reviewed alert" : "Right-click this alert"}</button>\n</ContextMenu>',
    },
    'components-lists-contextmenu',
  ),

  entry(
    'banner',
    'Banner',
    'Feedback',
    'Keep a relevant message visible beside the work it affects.',
    'Choose an intent and optionally supply a title, action, or dismiss callback. Use a visible message for information that must not depend on hover.',
    ['Intent icon', 'Title', 'Message', 'Optional action', 'Dismiss control'],
    {
      exports: 'Banner',
      setup: 'const [visible, setVisible] = useState(true);',
      jsx: '<div>\n  {visible && <Banner intent="warning" title="Partial data" onDismiss={() => setVisible(false)}>\n    Identity events are delayed by four minutes.\n  </Banner>}\n</div>',
    },
    'components-feedback-banner',
    [v('intent', ['info', 'success', 'warning', 'destroy', 'ai'], 'info')],
  ),
  entry(
    'empty-state',
    'Empty state',
    'Feedback',
    'Explain why a region is empty and provide a useful next step.',
    'Start with a no-results, no-data, or error preset; override title, description, and actions for the current task.',
    ['Illustrative icon', 'Title', 'Description', 'Primary and secondary actions'],
    {
      exports: 'EmptyState',
      imports: [buttonImport],
      setup: 'const [filtered, setFiltered] = useState(true);',
      jsx: '<EmptyState preset={filtered ? "no-results" : "no-data"}\n  title={filtered ? "No alerts match" : "No alerts yet"}\n  action={filtered ? <Button onClick={() => setFiltered(false)}>Clear filters</Button> : undefined} />',
    },
    'components-feedback-empty-state',
    [
      v('preset', ['no-results', 'no-data', 'error'], 'no-results'),
      v('compact', ['false', 'true'], 'false'),
    ],
  ),
  entry(
    'spinner',
    'Spinner',
    'Feedback',
    'Indicate brief work without shifting the surrounding layout.',
    'Give a standalone spinner a label. Omit it when a containing button already announces the operation.',
    ['Rotating indicator', 'Optional live label'],
    { exports: 'Spinner', jsx: '<Spinner size="md" label="Loading related events" />' },
    'components-feedback-spinner',
    [sizes],
  ),
  entry(
    'skeleton',
    'Skeleton',
    'Feedback',
    'Reserve the shape of content while it is loading.',
    'Match the expected content with text, block, avatar, or table-row shapes. The decorative skeleton should accompany a named loading region.',
    ['Placeholder shape', 'Optional shimmer'],
    {
      exports: 'Skeleton',
      jsx: '<div aria-busy="true" aria-label="Loading alert summary">\n  <Skeleton variant="text" width="70%" />\n  <Skeleton variant="text" width="90%" />\n  <Skeleton variant="block" height={96} />\n</div>',
    },
    'components-feedback-skeleton',
    [v('variant', ['text', 'block', 'avatar', 'table-row'], 'text')],
  ),
  entry(
    'progress-bar',
    'Progress bar',
    'Feedback',
    'Show how much of a bounded operation is complete.',
    'Provide value and max for measurable progress. Omit value for an indeterminate operation and always supply a label.',
    ['Accessible progress label', 'Track', 'Progress fill', 'Optional value'],
    {
      exports: 'ProgressBar',
      jsx: '<ProgressBar label="Replay progress" value={64} max={100} showValue />',
    },
    'components-feedback-progress-bar',
    [
      v('size', ['sm', 'md'], 'md'),
      v('intent', ['function', 'success', 'warning', 'destroy', 'ai'], 'function'),
    ],
  ),
  entry(
    'toast',
    'Toast',
    'Feedback',
    'Confirm an action without interrupting the current workflow.',
    'Mount Toaster once, then call showToast. Static Toast is also exported for inline presentations and custom integrations.',
    ['Intent icon', 'Title and description', 'Optional action', 'Dismiss control'],
    {
      exports: 'Toaster, showToast',
      imports: [buttonImport],
      jsx: '<>\n  <Button onClick={() => showToast({ title: "Rule saved", intent: "success",\n    description: "The rule remains disabled until you enable it." })}>Save rule</Button>\n  <Toaster />\n</>',
    },
    'components-feedback-toast',
    [v('intent', ['info', 'success', 'warning', 'destroy', 'ai', 'loading'], 'info')],
  ),

  entry(
    'card',
    'Card',
    'Layout',
    'Group related content into a surface with a clear internal hierarchy.',
    'Compose header, title, description, content, and footer slots. Shared spacing tokens keep related cards aligned.',
    ['Surface', 'Header', 'Title and description', 'Content', 'Footer'],
    {
      exports: 'Card, CardHeader, CardTitle, CardDescription, CardContent',
      jsx: '<Card>\n  <CardHeader><CardTitle>Detection coverage</CardTitle>\n    <CardDescription>Production endpoints</CardDescription></CardHeader>\n  <CardContent>142 of 150 endpoints reporting</CardContent>\n</Card>',
    },
    'components-surfaces-card',
    [v('elevation', ['flat', 'raised', 'floating'], 'raised')],
  ),
  entry(
    'accordion',
    'Accordion',
    'Layout',
    'Reveal supporting detail in compact, consistently nested sections.',
    'Use type single with a string value, or multiple with an array. Items can include icons, counts, and disabled states.',
    ['Section trigger', 'Chevron', 'Optional icon and count', 'Inset content', 'Divider'],
    {
      exports: 'Accordion',
      jsx: '<Accordion type="multiple" defaultValue={["evidence"]} items={[\n  { value: "evidence", title: "Evidence", count: 6, content: <p>Six related process events.</p> },\n  { value: "context", title: "Context", content: <p>Observed on a production endpoint.</p> },\n]} />',
    },
    'components-lists-accordion',
    [v('type', ['single', 'multiple']), v('variant', ['divided', 'contained'], 'divided')],
  ),
  entry(
    'separator',
    'Separator',
    'Layout',
    'Mark a boundary without adding another container.',
    'Choose horizontal or vertical orientation and line or dot treatment. Decorative separators stay out of the accessibility tree.',
    ['Line or dot', 'Optional semantic boundary'],
    {
      exports: 'Separator',
      jsx: '<div>\n  <p>Detection details</p><Separator />\n  <p>Related evidence</p>\n</div>',
    },
    'components-surfaces-separator',
    [
      v('orientation', ['horizontal', 'vertical'], 'horizontal'),
      v('variant', ['line', 'dot'], 'line'),
      v('emphasis', ['light', 'normal'], 'normal'),
    ],
  ),
  entry(
    'resizable-panels',
    'Resizable panels',
    'Layout',
    'Let people allocate space to the parts of a workspace they need most.',
    'Compose panels and labeled handles. Percentage strings express proportional sizes; numeric sizes are pixels. Handles support pointer and keyboard input.',
    ['Panel group', 'Panel', 'Labeled resize handle', 'Optional grip'],
    {
      exports: 'ResizablePanels, ResizablePanel, ResizeHandle',
      jsx: '<ResizablePanels orientation="horizontal" style={{ height: 240 }}>\n  <ResizablePanel defaultSize="60%" minSize="25%"><p>Alert queue</p></ResizablePanel>\n  <ResizeHandle label="Resize queue and evidence" />\n  <ResizablePanel defaultSize="40%" minSize="20%"><p>Evidence</p></ResizablePanel>\n</ResizablePanels>',
    },
    'components-layout-resizablepanels',
    [v('orientation', ['horizontal', 'vertical'], 'horizontal')],
  ),
  entry(
    'scroll-area',
    'Scroll area',
    'Layout',
    'Bound a long region while preserving normal keyboard and touch scrolling.',
    'Set maxHeight and a descriptive label. Scrollbars use the shared theme and appear while the region is being used.',
    ['Focusable scroll region', 'Content', 'Shared scrollbar'],
    {
      exports: 'ScrollArea',
      jsx: '<ScrollArea label="Related events" maxHeight={160}>\n  {Array.from({ length: 12 }, (_, index) => <p key={index}>Process event {index + 1}</p>)}\n</ScrollArea>',
    },
    'components-utilities-scrollarea',
  ),

  entry(
    'ai-card',
    'AI card',
    'AI',
    'Separate generated analysis from the evidence and decisions around it.',
    'Add confidence and provenance when available. Feedback and regeneration are optional explicit callbacks; the component does not call a model.',
    ['AI marker', 'Title', 'Generated content', 'Confidence', 'Provenance', 'Feedback actions'],
    {
      exports: 'AiCard',
      jsx: '<AiCard title="Suggested next step" confidence="medium" provenance="Based on six process events">\n  <p>Review the parent document and command line before closing this alert.</p>\n</AiCard>',
    },
    'components-ai-aicard',
    [confidence, v('loading', ['false', 'true'], 'false')],
  ),
  entry(
    'ai-highlight',
    'AI highlight',
    'AI',
    'Mark a short generated observation within a larger view.',
    'Use this compact surface for an attributed suggestion, with optional confidence and provenance. Keep consequential actions separate.',
    ['AI marker', 'Highlighted text', 'Confidence', 'Provenance'],
    {
      exports: 'AiHighlight',
      subpath: 'ai-card',
      jsx: '<AiHighlight confidence="high" provenance="Process tree and command line">\n  The document process launched an encoded PowerShell command.\n</AiHighlight>',
    },
    'components-ai-aihighlight',
    [confidence],
  ),
  entry(
    'ai-inline-suggestion',
    'AI inline suggestion',
    'AI',
    'Offer a proposed field value while keeping acceptance under user control.',
    'suggestion is the complete proposed value. Tab or the Accept button applies it; Escape dismisses it. Field context supplies labels and validation.',
    ['Input or textarea', 'Ghost suggestion', 'AI marker', 'Accept action', 'Dismiss action'],
    {
      exports: 'AiInlineSuggestion',
      setup: 'const [value, setValue] = useState("Suspicious");',
      jsx: '<AiInlineSuggestion label="Rule title" value={value} onValueChange={setValue}\n  suggestion="Suspicious PowerShell launched from Office" />',
    },
    'components-ai-aiinlinesuggestion',
    [v('as', ['input', 'textarea'], 'input'), sizes],
  ),
  entry(
    'ai-message',
    'AI message',
    'AI',
    'Present an assistant response with its working steps and cited context.',
    'Pass a structured AiMessageData object. Markdown is rendered without executing raw HTML; streaming and error states are explicit data.',
    ['Role label', 'Working steps', 'Message content', 'Citations', 'Feedback and copy controls'],
    {
      exports: 'AiMessage',
      jsx: '<AiMessage message={{ id: "analysis-1", role: "assistant", status: "complete",\n  content: "Review the **parent process** before resolving this alert.",\n  context: [], steps: [{ id: "step-1", label: "Read process events", status: "complete" }],\n  citations: [], timestamp: "2026-10-06T09:30:00Z", provenance: "Local example" }} />',
    },
    'components-ai-aimessage',
    [v('role', ['user', 'assistant']), v('status', ['streaming', 'complete', 'stopped', 'error'])],
  ),
  entry(
    'confidence-badge',
    'Confidence badge',
    'AI',
    'Make the stated confidence of an AI result visible and qualified.',
    'Use high, medium, or low consistently. Confidence is supporting context, not approval to act.',
    ['Confidence marker', 'Level label', 'Explanation tooltip'],
    { exports: 'ConfidenceBadge', jsx: '<ConfidenceBadge confidence="medium" />' },
    'components-ai-confidencebadge',
    [confidence],
  ),
  entry(
    'thinking-indicator',
    'Thinking indicator',
    'AI',
    'Show that an assistant is working without inventing progress percentages.',
    'Provide brief messages that accurately describe the current work. compact fits tighter chat layouts.',
    ['Activity marker', 'Rotating status message'],
    {
      exports: 'ThinkingIndicator',
      jsx: '<ThinkingIndicator messages={["Reading selected evidence", "Preparing the response"]} />',
    },
    'components-ai-thinkingindicator',
    [v('compact', ['false', 'true'], 'false')],
  ),
  entry(
    'streaming-skeleton',
    'Streaming skeleton',
    'AI',
    'Reserve space while generated content starts to arrive.',
    'Choose text or card layout and an honest loading label. Replace it with actual content as your stream updates.',
    ['AI activity treatment', 'Text lines or card shape', 'Loading label'],
    {
      exports: 'StreamingSkeleton',
      jsx: '<StreamingSkeleton lines={3} variant="text" label="Preparing analysis" />',
    },
    'components-ai-streamingskeleton',
    [v('variant', ['text', 'card'], 'text')],
  ),

  entry(
    'aws-logo',
    'AWS logos',
    'Brand & icons',
    'Identify AWS services and resources with their official architecture artwork.',
    'Import this optional subpath only where AWS assets are needed. Choose a catalogued name and use a meaningful label unless the logo is decorative.',
    ['Official SVG artwork', 'Accessible label', 'Optional service caption'],
    {
      exports: 'AwsLogo',
      jsx: '<AwsLogo name="service-amazon-ec2" size={48} label="Amazon EC2" />',
    },
    'components-brand-aws-logos',
    [v('size', ['24', '32', '40', '48', '64', '80'], '48')],
    ['cloud', 'architecture'],
  ),
  entry(
    'icons',
    'Icons',
    'Brand & icons',
    'Use a consistent set of semantic icons across actions and information.',
    'Import named icons from the public adapter. Decorative icons should be hidden from assistive technology; controls still need their own text label.',
    ['SVG graphic', 'Stroke', 'Accessible or decorative treatment'],
    {
      exports: 'Shield, Search, FileCode2',
      subpath: 'icons',
      jsx: '<div style={{ display: "flex", gap: 16 }}>\n  <span><Shield size={20} aria-hidden="true" /> Security</span>\n  <span><Search size={20} aria-hidden="true" /> Search</span>\n  <span><FileCode2 size={20} aria-hidden="true" /> Rules</span>\n</div>',
    },
    'foundations-icons',
    [v('size', ['16', '20', '24'])],
    ['hugeicons', 'symbols'],
  ),
];
